[package]
name = "wssblivedm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

 

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10.0"
log = "0.4.17"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
tokio-tungstenite = "*"
futures-channel = "0.3.28"
hyper = { version = "0.14.25", default-features = false, features = ["http1", "server", "tcp"] }
tokio = { version = "1.27.0", default-features = false, features = ["io-std", "macros", "net", "rt-multi-thread", "time","io-util"] }
url = "2.3.1"
http = "0.2.2"
bytes = "*"
awc = "3.1.1"
reqwest = { version = "0.11.17", features = ["json","blocking"] }
openssl = "0.10.29"
os_str_bytes = "6.5.1"
alloc-stdlib = "0.2.2"
huffman="0.0.3"
alloc-no-stdlib = "2.0.3"
brotlic = "0.8.1"

native-tls="0.2.0"
 

[dependencies.tungstenite]
version = "0.19.0"
default-features = false