[package]
name = "danmu"
version = "0.1.0"
edition = "2024"

[dependencies]
client = { path = "../client" }
plugins = { path = "../plugins" }
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
log = "0.4"
env_logger = "0.11.8"
