name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: previoustag
        run: |
          echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo '')" >> $GITHUB_ENV
          echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_notes
        run: |
          if [ -n "$PREVIOUS_TAG" ]; then
            echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
            echo "## Changes since $PREVIOUS_TAG" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%an) [%h](https://github.com/${{ github.repository }}/commit/%H)" $PREVIOUS_TAG..$CURRENT_TAG >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "## Building from Source" >> $GITHUB_ENV
            echo "\`\`\`bash" >> $GITHUB_ENV
            echo "# Clone the repository" >> $GITHUB_ENV
            echo "git clone https://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
            echo "cd blivedm_rs" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "# Build the project" >> $GITHUB_ENV
            echo "cargo build --release" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "# Run the danmu client (auto-detect cookies from browser)" >> $GITHUB_ENV
            echo "./target/release/danmu --room-id <ROOM_ID>" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "# Or with manual cookies (must include SESSDATA)" >> $GITHUB_ENV
            echo "./target/release/danmu --cookies \"SESSDATA=your_sessdata; other_cookie=...\" --room-id <ROOM_ID>" >> $GITHUB_ENV
            echo "\`\`\`" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "## System Requirements" >> $GITHUB_ENV
            echo "- **Rust**: Latest stable version" >> $GITHUB_ENV
            echo "- **Linux**: \`espeak-ng\` for TTS support (\`sudo apt-get install espeak-ng\`)" >> $GITHUB_ENV
            echo "- **macOS**: Built-in \`say\` command (no additional dependencies)" >> $GITHUB_ENV
            echo "- **Audio dependencies**: \`alsa-dev\` on Linux, \`pkg-config\`, \`libssl-dev\`" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
            echo "## Initial Release" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "### Features" >> $GITHUB_ENV
            echo "- Bilibili live stream danmu (comment) monitoring" >> $GITHUB_ENV
            echo "- Text-to-Speech (TTS) support with multiple backends" >> $GITHUB_ENV
            echo "- REST API TTS integration with configurable voices" >> $GITHUB_ENV
            echo "- Command-line TTS support (espeak-ng, say)" >> $GITHUB_ENV
            echo "- Terminal display plugin for danmu messages" >> $GITHUB_ENV
            echo "- Configurable audio volume control" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "### Recent Commits" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%an) [%h](https://github.com/${{ github.repository }}/commit/%H)" --max-count=10 >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "## Building from Source" >> $GITHUB_ENV
            echo "\`\`\`bash" >> $GITHUB_ENV
            echo "# Clone the repository" >> $GITHUB_ENV
            echo "git clone https://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
            echo "cd blivedm_rs" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "# Build the project" >> $GITHUB_ENV
            echo "cargo build --release" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "# Run the danmu client (auto-detect cookies from browser)" >> $GITHUB_ENV
            echo "./target/release/danmu --room-id <ROOM_ID>" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "# Or with manual cookies (must include SESSDATA)" >> $GITHUB_ENV
            echo "./target/release/danmu --cookies \"SESSDATA=your_sessdata; other_cookie=...\" --room-id <ROOM_ID>" >> $GITHUB_ENV
            echo "\`\`\`" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "## System Requirements" >> $GITHUB_ENV
            echo "- **Rust**: Latest stable version" >> $GITHUB_ENV
            echo "- **Linux**: \`espeak-ng\` for TTS support (\`sudo apt-get install espeak-ng\`)" >> $GITHUB_ENV
            echo "- **macOS**: Built-in \`say\` command (no additional dependencies)" >> $GITHUB_ENV
            echo "- **Audio dependencies**: \`alsa-dev\` on Linux, \`pkg-config\`, \`libssl-dev\`" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          name: Release ${{ steps.tag_name.outputs.TAG_NAME }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
